#ifndef PIPELINEEDITDIALOG_H
#define PIPELINEEDITDIALOG_H

#include <QDialog>
#include <QLineEdit>
#include <QComboBox>
#include <QDoubleSpinBox>
#include <QTextEdit>
#include <QDateEdit>
#include "core/models/pipeline.h"

/**
 * @brief 管线属性编辑对话框
 * 
 * 用于创建或编辑管线的属性信息
 */
class PipelineEditDialog : public QDialog
{
    Q_OBJECT

public:
    explicit PipelineEditDialog(QWidget *parent = nullptr);
    ~PipelineEditDialog();

    /**
     * @brief 设置管线类型（用于新建）
     */
    void setPipelineType(const QString &type);
    
    /**
     * @brief 设置管线编号（自动生成）
     */
    void setAutoGeneratedCode(int id, const QString &type);
    
    /**
     * @brief 设置 WKT 几何数据
     */
    void setGeometry(const QString &wkt);
    
    /**
     * @brief 计算并设置管线长度
     */
    void calculateAndSetLength(const QVector<QPointF> &points);
    
    /**
     * @brief 使用地理坐标计算并设置管线长度
     */
    void calculateAndSetLengthFromWKT(const QString &wkt);
    
    /**
     * @brief 获取管线对象
     */
    Pipeline getPipeline() const;
    
    /**
     * @brief 加载已有管线数据（用于编辑）
     */
    void loadPipeline(const Pipeline &pipeline);

private slots:
    void onAccepted();
    void onRejected();

private:
    void setupUI();
    void setupConnections();
    QString getTypeDisplayName(const QString &typeId) const;
    
    // 基本信息
    QLineEdit *m_idEdit;                // 管线ID（只读）
    QLineEdit *m_nameEdit;              // 管线名称
    QComboBox *m_typeCombo;             // 管线类型
    QLineEdit *m_codeEdit;              // 管线编号
    
    // 物理属性
    QDoubleSpinBox *m_diameterSpin;     // 管径(mm)
    QComboBox *m_materialCombo;         // 材质
    QDoubleSpinBox *m_lengthSpin;       // 长度(m)
    QDoubleSpinBox *m_depthSpin;        // 埋深(m)
    QComboBox *m_pressureCombo;         // 压力等级
    
    // 建设信息
    QDateEdit *m_constructionDateEdit;  // 建设日期
    QLineEdit *m_constructorEdit;       // 施工单位
    QComboBox *m_statusCombo;           // 运行状态
    
    // 备注
    QTextEdit *m_remarkEdit;            // 备注
    
    // 数据
    QString m_wktGeometry;              // WKT几何数据
    int m_id;                           // 管线ID（编辑时使用）
};

#endif // PIPELINEEDITDIALOG_H
